import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  JavaSidebar: [{ type: "autogenerated", dirName: "java" }],
  ToolsSidebar: [{ type: "autogenerated", dirName: "tools" }],
  DockerSidebar: [{ type: "autogenerated", dirName: "tools/docker" }],

  FundamentalSidebar: [{ type: "autogenerated", dirName: "fundamental" }],
  
  
  AISidebar: [{ type: "autogenerated", dirName: "artificial-intelligence" }],
  FrontEndSidebar: [{ type: "autogenerated", dirName: "front-end" }],
  ReactSidebar: [{ type: "autogenerated", dirName: "front-end/react" }],
  ConstructSidebar: [{ type: "autogenerated", dirName: "front-end/construct" }],
  CaseStudySidebar: [
    { type: "autogenerated", dirName: "front-end/case-study" },
  ],

  DataBaseSidebar: [{ type: "autogenerated", dirName: "database" }],
  MysqlSidebar: [{ type: "autogenerated", dirName: "database/mysql" }],
  SqlSidebar: [{ type: "autogenerated", dirName: "database/sql" }],
  ES6Sidebar: [{ type: "autogenerated", dirName: "front-end/es6" }],

  BigDataSidebar: [{ type: "autogenerated", dirName: "big-data" }],
  MaxwellSidebar: [{ type: "autogenerated", dirName: "big-data/maxwell" }],
  DataXSidebar: [{ type: "autogenerated", dirName: "big-data/datax" }],
  FlumeSidebar: [{ type: "autogenerated", dirName: "big-data/flume" }],
  HadoopSidebar: [{ type: "autogenerated", dirName: "big-data/hadoop" }],
  CoreConceptSidebar: [
    { type: "autogenerated", dirName: "big-data/core-concept" },
  ],
  HiveSidebar: [{ type: "autogenerated", dirName: "big-data/hive" }],
  ZookeeperSidebar: [{ type: "autogenerated", dirName: "big-data/zookeeper" }],
  BigDataToolsSidebar:[{type: "autogenerated", dirName: "big-data/tools"}],
  
  PythonSidebar: [{ type: "autogenerated", dirName: "python" }],
  EffectivePythonSidebar: [
    { type: "autogenerated", dirName: "python/effective-python" },
  ],

  AlgorithmSidebar: [{ type: "autogenerated", dirName: "algorithm" }],
  ArraySidebar: [{ type: "autogenerated", dirName: "algorithm/array" }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
